#Redis hosted in Azure. For simplicity non SSL port is open.
#In a prod service, use TLS port.
REDIS:
  hostname: 'malwareDb.redis.cache.windows.net' 
  port: 6379
  key: 'QVacmRpAGQZMAJRuxqX9jZ1Ma60pL5cTZAzCaFe9aR4='

# User list can be moved to a db if we have use case for multiple users.
# In a prod service, we should use token based auth. 
USERS:
#List of users with username as key and hashed password as value. 
#For testing, password for user 'default' is 'someComplexPassword'
  default: '$2b$12$mix29YjcVnpv9JEPbrZloeS.yuo23HZwCTmmx50wevY8mvNOWzoVG'